export default [
    {
        name: "Allan Munger",
        avatar: require('./avatars/AllanMunger.png'),
        role: "Principal Tactics Liaison",
        about: "Sint rerum sequi exercitationem sed quas consequatur tempore nobis dolor. Ut dolores illo. Debitis aut ut rerum deserunt mollitia repellat corporis consequatur magnam. Voluptates adipisci deserunt et. Quisquam quo ut repellendus reiciendis. Ut sed sunt.",
    },
    {
        name: "Amanda Brady",
        avatar: require('./avatars/AmandaBrady.png'),
        role: "Customer Implementation Coordinator",
        about: "Et quia laudantium. Consequatur nam modi voluptas est eius. Mollitia in neque laudantium aliquid et ratione. Magnam dolorum hic. Non in aut neque amet ducimus ad. Odio qui ducimus voluptatem.",
    },
    {
        name: "Ashley Mc Carthy",
        avatar: require('./avatars/AshleyMcCarthy.png'),
        role: "Investor Accounts Manager",
        about: "Porro in cumque nesciunt et. Ut iusto et molestias. Excepturi debitis nisi nulla quasi non. Dignissimos minima aut enim aut et ullam error quo. Enim eum sunt ut recusandae corporis repudiandae nostrum. Ratione iusto non non enim dolores quidem.",
    },
    {
        name: "Carlos Slattery",
        avatar: require('./avatars/CarlosSlattery.png'),
        role: "Customer Identity Liaison",
        about: "Deleniti iste magnam iste ut officiis. Sequi animi ut. Sed minima odio rerum.",
    },
    {
        name: "Carole Poland",
        avatar: require('./avatars/CarolePoland.png'),
        role: "Forward Communications Coordinator",
        about: "Soluta voluptatem qui quis est reiciendis non dignissimos necessitatibus dicta. Aliquid incidunt ut dolorum sed ut quisquam. Ad quaerat libero fugiat molestiae ea itaque. Sed harum perspiciatis voluptatem ullam sunt dolor. Aliquam numquam ut quod quia rerum quae. Porro vitae velit possimus quae incidunt et perferendis.",
    },
    {
        name: "Cecil Folk",
        avatar: require('./avatars/CecilFolk.png'),
        role: "Direct Functionality Representative",
        about: "Asperiores beatae possimus. Quos omnis pariatur. Cumque autem nemo. Aut debitis eius consequatur quae pariatur itaque optio et. Asperiores sint consequatur vitae doloribus sunt velit. Et dolorem alias quia.",
    },
    {
        name: "Celeste Burton",
        avatar: require('./avatars/CelesteBurton.png'),
        role: "Product Paradigm Orchestrator",
        about: "Modi voluptas sint error quis. Deserunt nemo numquam ut delectus. In dolores velit nemo dolores omnis ullam beatae illo necessitatibus. Mollitia natus odit laudantium nobis consequatur quisquam et autem. Quam accusamus tenetur autem odit voluptatem ad.",
    },
    {
        name: "Charlotte Waltson",
        avatar: require('./avatars/CharlotteWaltson.png'),
        role: "Corporate Branding Planner",
        about: "Quidem sit voluptas distinctio sint. Itaque non non officiis consequatur dolorum dolores. Cum quo minima quis.",
    },
    {
        name: "Colin Ballinger",
        avatar: require('./avatars/ColinBallinger.png'),
        role: "Senior Markets Coordinator",
        about: "Totam sed amet ducimus non nihil est. Delectus id vel vel est et sed suscipit non. Nemo accusantium voluptate dolor. Quis sed numquam et rerum voluptates alias aut sunt.",
    },
    {
        name: "Daisy Phillips",
        avatar: require('./avatars/DaisyPhillips.png'),
        role: "Corporate Response Orchestrator",
        about: "Et et tempora illo eveniet autem iste fuga molestiae est. Iusto et impedit iure. Consequatur similique est accusantium in aspernatur nisi.",
    },
    {
        name: "Elliot Woodward",
        avatar: require('./avatars/ElliotWoodward.png'),
        role: "International Implementation Facilitator",
        about: "Fugit dolor iste consequuntur iure fuga nesciunt. Aut consequatur quia quo asperiores. Error molestiae quisquam nesciunt sint at est architecto corrupti qui. In ratione et perspiciatis. Voluptas facilis nulla.",
    },
    {
        name: "Elvia Atkins",
        avatar: require('./avatars/ElviaAtkins.png'),
        role: "Human Research Executive",
        about: "Autem dolor sit nisi quo. Nisi qui voluptas soluta deserunt maxime nihil officiis magni. Est eaque omnis iure officia nam.",
    },
    {
        name: "Erik Nason",
        avatar: require('./avatars/ErikNason.png'),
        role: "Legacy Accounts Strategist",
        about: "Vel ut nam. Suscipit consequuntur suscipit omnis qui quam doloremque. Repudiandae et sint rerum neque et vero. Quaerat et non. Magni similique iure esse recusandae.",
    },
    {
        name: "Henry Brill",
        avatar: require('./avatars/HenryBrill.png'),
        role: "Investor Metrics Associate",
        about: "Sed quisquam aut ut facere illo voluptatem. Asperiores assumenda consectetur. Minima aut molestias ullam corporis harum sed recusandae et. Ratione veniam qui.",
    },
    {
        name: "Isaac Fielder",
        avatar: require('./avatars/IsaacFielder.png'),
        role: "District Optimization Facilitator",
        about: "Neque repellendus et. Et et tenetur. Est hic vero distinctio ipsum tempore vitae deleniti perspiciatis cum. Sunt minima sit vero ipsum voluptatem molestiae enim consequuntur. Nostrum expedita alias dolores et sapiente exercitationem aut quia.",
    },
    {
        name: "Johnie McConnell",
        avatar: require('./avatars/JohnieMcConnell.png'),
        role: "Regional Brand Technician",
        about: "Dolorem et qui qui omnis quis. Suscipit sunt blanditiis. Quos nisi iure nulla eius eum eaque ipsam. Repellendus consequatur atque delectus debitis quis et et.",
    },
    {
        name: "Kat larsson",
        avatar: require('./avatars/Katlarsson.png'),
        role: "Dynamic Assurance Agent",
        about: "Sit iste aut quia voluptatem. Est eos adipisci deserunt sequi ut maxime qui est molestiae. Doloribus iure ut repellendus et. Dolorum sint et at.",
    },
    {
        name: "Katri Ahokas",
        avatar: require('./avatars/KatriAhokas.png'),
        role: "Investor Solutions Orchestrator",
        about: "Cumque voluptates ducimus molestiae illum ut modi. Eligendi quia temporibus eligendi unde quaerat. Aut enim architecto. Deleniti quod est aspernatur. Cupiditate eum nesciunt ut repellat dolorem adipisci sunt.",
    },
    {
        name: "Kevin Sturgis",
        avatar: require('./avatars/KevinSturgis.png'),
        role: "Principal Program Consultant",
        about: "Temporibus atque odit quaerat ea rem qui corrupti. Rerum exercitationem eius magni. Delectus totam nihil non eos quod dicta nisi accusantium ullam. Et impedit occaecati fugit deserunt magnam et.",
    },
    {
        name: "Kristin Patterson",
        avatar: require('./avatars/KristinPatterson.png'),
        role: "International Metrics Producer",
        about: "Illo repudiandae praesentium quia magnam voluptatum pariatur maiores. Ex qui perspiciatis ut voluptate illo amet facilis consequatur fugiat. Non facilis molestiae autem.",
    },
    {
        name: "Lydia Bauer",
        avatar: require('./avatars/LydiaBauer.png'),
        role: "Forward Response Officer",
        about: "Cum et vel vel ipsa. Delectus odit praesentium. Inventore laborum omnis aut saepe sint. Nesciunt id aperiam quod in.",
    },
    {
        name: "Mauricio August",
        avatar: require('./avatars/MauricioAugust.png'),
        role: "Chief Brand Supervisor",
        about: "Explicabo repellat est dolores. Perferendis quibusdam omnis voluptatibus autem incidunt totam aperiam. Reprehenderit odio occaecati consequatur eum aut qui. Sit beatae rerum dolorem eos sapiente est et. Voluptas non similique eos mollitia. Blanditiis consequatur rerum quos sunt blanditiis quisquam nam voluptates.",
    },
    {
        name: "Miguel Garcia",
        avatar: require('./avatars/MiguelGarcia.png'),
        role: "National Response Agent",
        about: "Id qui neque sit et a nesciunt. Magni provident dolores deserunt natus assumenda officiis consequatur amet aliquid. Ipsam commodi quis expedita repellat praesentium maiores autem. Eveniet autem reprehenderit velit dolore quod totam ut non. Et et ipsum eum ratione molestiae ea molestiae.",
    },
    {
        name: "Mona Kane",
        avatar: require('./avatars/MonaKane.png'),
        role: "Lead Division Facilitator",
        about: "Repellendus repudiandae sed atque velit saepe. Sint enim quisquam molestiae. Accusamus nihil architecto omnis. Et nihil aut voluptate et illo exercitationem rerum eius consequatur. Earum voluptates voluptatum. Quibusdam repellat illo fuga nihil fuga.",
    },
    {
        name: "Robert Tolbert",
        avatar: require('./avatars/RobertTolbert.png'),
        role: "Regional Functionality Director",
        about: "Quam optio eligendi dolores et. Unde saepe harum sapiente. Labore et voluptas vel. Quia quo omnis. Pariatur maiores modi totam praesentium cumque eius mollitia autem. Recusandae explicabo dolorum tempora deserunt in.",
    },
    {
        name: "Robin Counts",
        avatar: require('./avatars/RobinCounts.png'),
        role: "Forward Configuration Engineer",
        about: "Ab sit et quibusdam et aut ab et rerum. Unde quae vero similique natus. Ea eum voluptatibus. Minus ut suscipit voluptatem vel aspernatur corrupti rerum. Porro impedit dolorem natus.",
    },
    {
        name: "Tim Deboer",
        avatar: require('./avatars/TimDeboer.png'),
        role: "Dynamic Usability Specialist",
        about: "Nisi ea officia est adipisci placeat dolorem. Repudiandae voluptas adipisci error aspernatur. Est sint labore animi. Ipsam et vitae est doloribus ipsam voluptatibus dolor nostrum et. Iusto recusandae doloremque. Reiciendis expedita non.",
    },
    {
        name: "Wanda Howard",
        avatar: require('./avatars/WandaHoward.png'),
        role: "Human Integration Developer",
        about: "Animi iusto non repellat. Alias nobis dignissimos perspiciatis ab. Adipisci excepturi quod dicta et exercitationem neque distinctio sunt voluptate. Ut iusto quaerat fugit aperiam.",
    }]